# Generated by Django 3.2.4 on 2021-12-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visyon', models.CharField(blank=True, max_length=64, null=True)),
                ('misyon', models.CharField(blank=True, max_length=64, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('phone', models.IntegerField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='employee')),
                ('profession', models.CharField(blank=True, max_length=64, null=True)),
                ('experience', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.FloatField(blank=True, max_length=7, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='urunler')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('XS', 'XS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=64, null=True)),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Migros.category')),
            ],
        ),
    ]
