# Generated by Django 3.2.4 on 2021-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='birim',
            field=models.CharField(blank=True, choices=[('TL', 'TL'), ('$', '$'), ('Euro', 'Euro')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
