# Generated by Django 3.2.4 on 2021-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0004_calisan_hastalik_ilac_recete'),
    ]

    operations = [
        migrations.AddField(
            model_name='recete',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
