# Generated by Django 3.2.4 on 2021-12-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0005_recete_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calisan',
            old_name='name',
            new_name='calisan_name',
        ),
        migrations.RenameField(
            model_name='hastalik',
            old_name='name',
            new_name='hastali_name',
        ),
        migrations.RenameField(
            model_name='ilac',
            old_name='name',
            new_name='ilac_name',
        ),
        migrations.RenameField(
            model_name='recete',
            old_name='name',
            new_name='hasta_adi',
        ),
    ]
