# Generated by Django 3.2.4 on 2021-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0006_auto_20211221_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
