# Generated by Django 3.2.4 on 2021-12-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0007_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastalik',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='hastalik',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='ilac',
            name='r_id',
        ),
        migrations.DeleteModel(
            name='Calisan',
        ),
        migrations.DeleteModel(
            name='Hastalik',
        ),
        migrations.DeleteModel(
            name='ilac',
        ),
        migrations.DeleteModel(
            name='Recete',
        ),
    ]
