# Generated by Django 3.2.4 on 2021-12-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0008_auto_20211221_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='experience1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience2',
            field=models.TextField(default='adasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience3',
            field=models.TextField(default='sdcsdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
