# Generated by Django 3.2.4 on 2021-12-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0011_auto_20211228_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urunler',
            options={'ordering': ['-date']},
        ),
    ]
