# Generated by Django 3.2.4 on 2021-12-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0012_alter_urunler_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-name']},
        ),
    ]
