# Generated by Django 3.2.6 on 2022-05-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migros', '0013_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='tel',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
